[package]
name = "anchor-pyth"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "anchor_pyth"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
proc-macro2 = "=1.0.94"
pyth-solana-receiver-sdk = { path = "/Users/tejasbadadare/dev/pyth-crosschain/target_chains/solana/pyth_solana_receiver_sdk" }
# pyth-solana-receiver-sdk = { git = "https://github.com/pyth-network/pyth-crosschain", branch = "tb/solana-receiver-sdk/solana-program-2" }
